include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "example/lib/generated_plugin_registrant.dart"
  errors:
    todo: ignore

linter:
  rules:
    constant_identifier_names: false