name: analyticsx
description: Analytics solution for using multiple analytics vendors
version: 1.0.0
homepage: https://github.com/grahamsmith/analyticsx

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.6.0
  test: ^1.17.11
